import {writeFile} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),source=resolve(process.argv[2]);
const e=await import(pathToFileURL(resolve(source,'src/orbital-events.js')));
const t=await import(pathToFileURL(resolve(source,'src/time.js')));
const rows=[];
function add(kind,args,options={}) {rows.push({kind,args,options,result:e[kind](...args,options)});}
const jd=y=>t.julianDay({year:y,month:1,day:1});
for(const year of [-1000,2000,2026,5000]) {
 add('searchLunarApsides',[jd(year),jd(year)+65]);
 add('searchEarthApsides',[jd(year),jd(year)+370]);
 for(const frame of ['j2000','mean-of-date','true-of-date']) add('searchLunarNodes',[jd(year),jd(year)+65],{frame});
}
for(const frame of ['j2000','mean-of-date','true-of-date']) for(const accuracy of ['fast','mid','accurate']) {
 const options={apparent:{frame,accuracy}};
 add('searchGreatestElongations',['mercury',jd(2026),jd(2027)],options);
 add('searchRightAscensionStations',['mercury',jd(2026),jd(2027)],options);
 add('searchRelativeRightAscension',['moon','sun',0,jd(2026),jd(2026)+65],options);
}
add('searchGreatestElongations',['venus',jd(2024),jd(2027)]);
add('searchRelativeRightAscension',['jupiter','sun',180,jd(2026),jd(2027)]);
add('searchRightAscensionStations',['mars',jd(2025),jd(2026)]);
add('searchLunarApsides',[jd(2026),jd(2026)]);
add('searchLunarNodes',[jd(2026),jd(2026)+65],{stepDays:0.25,toleranceDays:1e-9});
await writeFile(resolve(root,'test/fixtures/orbital.json'),JSON.stringify(rows)+'\n');
console.log({queries:rows.length,events:rows.reduce((n,r)=>n+r.result.length,0)});

const subset=[0,1,2,3,4,20,24,28,47,48,49].map(i=>rows[i]);
await writeFile(resolve(root,'tool/orbital_portability_check.dart'),
`// GENERATED by tool/generate_orbital_oracles.mjs; format with dart format.
import 'dart:convert';
import '../test/orbital_support.dart';
void main() {
 final rows=jsonDecode(r\'\'\'${JSON.stringify(subset)}\'\'\') as List;
 for(final row in rows) {
  final actual=runOrbital(row as Map<String,dynamic>);
  final expected=row['result'] as List;
  if(actual.length!=expected.length) throw StateError('event count');
  for(var i=0;i<actual.length;i++) {compareOrbital(actual[i].toJson(),expected[i]);}
 }
 print('11 orbital searches passed in compiled JavaScript');
}
`);
