import {writeFile} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),source=resolve(process.argv[2]);
const e=await import(pathToFileURL(resolve(source,'src/eclipse-search.js'))),t=await import(pathToFileURL(resolve(source,'src/time.js')));
const jd=(y,m=1,d=1)=>t.julianDay({year:y,month:m,day:d});
const rows=[];
for(const y of [-1000,1000,1800,2000,2024,2025,2026,2200,5000]) {
 const args=[jd(y),jd(y+1)];rows.push({kind:'search',args,result:e.searchLunarEclipses(...args)});
}
for(const args of [[2025,3,14],[2025,9,7],[2026,8,28],[2024,3,25],[2026,1,1]]) {
 const date=jd(...args);rows.push({kind:'details',args:[date],result:e.getLunarEclipseDetails(date)});
}
for(const date of [jd(2025,3,14),jd(2025,9,7),jd(2026,8,28),jd(2024,3,25)]) {
 for(const [longitudeDeg,latitudeDeg] of [[116.4074,39.9042],[-74,40.7],[151.2,-33.9],[0,89]]) {
 const observer={longitudeDeg,latitudeDeg};rows.push({kind:'local',args:[date],observer,result:e.getLocalLunarEclipse(date,observer)});
 }
}
await writeFile(resolve(root,'test/fixtures/lunar_eclipses.json'),JSON.stringify(rows)+'\n');
const selected=[0,4,6,9,13,14,15,16,17].map(i=>rows[i]);
await writeFile(resolve(root,'tool/lunar_eclipse_portability_check.dart'),`// GENERATED by generate_lunar_eclipse_oracles.mjs; format with dart format.
import 'dart:convert';
import '../test/lunar_eclipse_support.dart';
void main() {final rows=jsonDecode(r'''${JSON.stringify(selected)}''') as List;for(final r in rows) {compareEclipse(runEclipse(r),r['result']);} print('9 lunar eclipse queries passed in compiled JavaScript');}
`);
console.log({queries:rows.length,globalEvents:rows.filter(r=>r.kind==='search').reduce((s,r)=>s+r.result.length,0)});
