// Development-only importer. Dart applications do not need JS or this checkout.
import { readFile, writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
const source = resolve(process.argv[2] ?? '../taiyin-lite');
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const load = name => import(pathToFileURL(resolve(source, 'src', name)));
const files = ['planet-series.js', 'planet-prefix-counts.js', 'earth-prefix-counts.js', 'moon-series.js', 'moon-prefix-counts.js', 'time.js'];
const [p, prefixes, earth, moon, moonPrefixes] = await Promise.all(files.slice(0,5).map(load));
const literal = value => {
  if (Array.isArray(value)) return `[${value.map(literal).join(',')}]`;
  if (typeof value === 'number') { if (!Number.isFinite(value)) throw Error('Non-finite coefficient'); return String(value); }
  if (typeof value === 'string') return JSON.stringify(value);
  if (value === null) return 'null';
  return `{${Object.entries(value).map(([k,v]) => `${JSON.stringify(k)}:${literal(v)}`).join(',')}}`;
};
let data = '// GENERATED by tool/import_js_data.mjs; do not edit. MPL-2.0.\n';
const planets = ['mercury','venus','earth','mars','jupiter','saturn','uranus','neptune'];
const series = {}, counts = {};
for (const name of planets) {
 const key = name.toUpperCase();
 series[name] = ['L','B','R'].map(axis=>p[`${key}_${axis}`]);
 counts[name] = name === 'earth'
  ? { fast:[earth.EARTH_L_PREFIX_COUNTS[60],null,earth.EARTH_R_PREFIX_COUNTS[30]],mid:[earth.EARTH_L_PREFIX_COUNTS[129],null,null] }
  : Object.fromEntries(['fast','mid'].map(tier=>[tier,prefixes[`${key}_PREFIX_COUNTS`].map(axis=>axis[tier])]));
}
data += `const planetSeries = <String,List<List<List<double>>>>>${literal(series)};\n`.replace('>>>>>','>>>>');
data += `const planetPrefixes = <String,Map<String,List<List<int>?>>>${literal(counts)};\n`;
for (const [key, dartName, type] of [
 ['MOON_L','moonL','List<List<double>>'], ['MOON_B','moonB','List<List<double>>'], ['MOON_R','moonR','List<List<double>>'],
 ['MOON_ARGUMENTS','moonArguments','List<List<double>>'], ['MOON_W1','moonW1','List<double>'],
 ['MOON_PRECESSION_P','moonPrecessionP','List<double>'],['MOON_PRECESSION_Q','moonPrecessionQ','List<double>'],
]) data += `const ${type} ${dartName} = ${literal(moon[key])};\n`;
data += `const double moonScaleDays = ${moon.MOON_SCALE_DAYS};\n`;
data += `const moonPrefixes = <Map<String,List<int>>>${literal(moonPrefixes.MOON_PREFIX_COUNTS)};\n`;
await writeFile(resolve(root,'lib/src/generated/series.dart'),data);
const time = await readFile(resolve(source,'src/time.js'),'utf8');
const table = name => JSON.parse(time.match(new RegExp(`const ${name} = (\\[[\\s\\S]*?\\n\\]);`))[1].replace(/,\s*]/g,']'));
await writeFile(resolve(root,'lib/src/generated/delta_t_data.dart'),
 '// GENERATED from JS time.js. See THIRD_PARTY_NOTICES.md.\n'+
 `const s15Spline = <List<double>>${literal(table('S15_SPLINE'))};\n`+
 `const annualDeltaT = <double>${literal(table('ANNUAL_DELTA_T'))};\n`);
const hashes = {};
for (const file of files) hashes[file]=createHash('sha256').update(await readFile(resolve(source,'src',file))).digest('hex');
await writeFile(resolve(root,'tool/upstream.json'),JSON.stringify({
 repository:'https://github.com/RedSC1/js-ephemeris-lite',
 commit:execFileSync('git',['rev-parse','HEAD'],{cwd:source,encoding:'utf8'}).trim(),
 files:hashes,
},null,2)+'\n');
console.log('Imported eight planetary series, Moon series, prefix counts, and Delta-T tables.');
