// Split the importer's legacy intermediate representation without changing values.
import {writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
export async function writeSplitSeries(root, data) {
  const header='// GENERATED by tool/import_js_data.mjs; do not edit. MPL-2.0.\n';
  const lines=data.trimEnd().split('\n');
  const parseMap=name=>{const line=lines.find(s=>s.startsWith(`const ${name} =`));return JSON.parse(line.slice(line.indexOf('{'),-1));};
  const planets=parseMap('planetSeries'),prefixes=parseMap('planetPrefixes');
  const bodies=Object.keys(planets);
  let aggregate=header;
  for(const name of bodies) {
    await writeFile(resolve(root,`lib/src/generated/${name}_series.dart`),header+
      `const ${name}Series = <List<List<double>>>${JSON.stringify(planets[name])};\n`+
      `const ${name}Prefixes = <String,List<List<int>?>>${JSON.stringify(prefixes[name])};\n`);
    aggregate+=`import '${name}_series.dart';\nexport '${name}_series.dart';\n`;
  }
  aggregate+=`const planetSeries = <String,List<List<List<double>>>>{${bodies.map(n=>`'${n}':${n}Series`).join(',')}};\n`;
  aggregate+=`const planetPrefixes = <String,Map<String,List<List<int>?>>>{${bodies.map(n=>`'${n}':${n}Prefixes`).join(',')}};\n`;
  await writeFile(resolve(root,'lib/src/generated/planet_series.dart'),aggregate);
  for(const kind of ['moon','pluto']) {
    const selected=lines.filter(l=>l.startsWith('const ')&&new RegExp(`\\b${kind}\\w*\\s*=`).test(l));
    await writeFile(resolve(root,`lib/src/generated/${kind}_series.dart`),header+selected.join('\n')+'\n');
  }
  await writeFile(resolve(root,'lib/src/generated/series.dart'),header+
    "// Compatibility aggregate for tools and existing internal consumers.\nexport 'planet_series.dart';\nexport 'moon_series.dart';\nexport 'pluto_series.dart';\n");
}
